## For more details on how to configure your build environment visit
# http://www.gradle.org/docs/current/userguide/build_environment.html
#
# Specifies the JVM arguments used for the daemon process.
# The setting is particularly useful for tweaking memory settings.
# Default value: -Xmx1024m -XX:MaxPermSize=256m
# org.gradle.jvmargs=-Xmx2048m -XX:MaxPermSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
#
# When configured, Gradle will run in incubating parallel mode.
# This option should only be used with decoupled projects. For more details, visit
# https://developer.android.com/r/tools/gradle-multi-project-decoupled-projects
org.gradle.parallel=true
#Sat Feb 14 12:53:07 IST 2026
GROUP=io.legere
POM_DESCRIPTION=Pdfium Android binding with Bitmap rendering ( >\= API 24 )
POM_DEVELOPER_ID=johngray1965
POM_DEVELOPER_NAME=John Gray
POM_LICENCE_DIST=repo
POM_LICENCE_NAME=The Apache Software License, Version 2.0
POM_LICENCE_URL=http\://www.apache.org/licenses/LICENSE-2.0.txt
POM_PACKAGING=aar
POM_SCM_CONNECTION=scm\:git@github.com\:johngray1965/PdfiumAndroidKt.git
POM_SCM_DEV_CONNECTION=scm\:git@github.com\:johngray1965/PdfiumAndroidKt.git
POM_SCM_URL=git@github.com\:johngray1965/PdfiumAndroidKt.git
POM_URL=https\://github.com/johngray1965/PdfiumAndroidKt
VERSION_CODE=6
VERSION_NAME=1.0.34
android.defaults.buildfeatures.resvalues=true
android.dependency.useConstraints=true
android.enableAppCompileTimeRClass=false
android.enableJetifier=false
android.nonTransitiveRClass=true
android.r8.optimizedResourceShrinking=false
android.r8.strictFullModeForKeepRules=false
android.sdk.defaultTargetSdkToCompileSdkIfUnset=false
android.uniquePackageNames=false
android.useAndroidX=true
android.usesSdkInManifest.disallowed=false
kotlin.code.style=official
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.jvmargs=-Xmx3072M -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -Dkotlin.daemon.jvm.options="-Xmx2048M" -XX:MaxMetaspaceSize=1024m -Dfile.encoding=UTF-8
org.gradle.vfs.watch=true
